### ISSUE TITLE
Phone number missing in signup form

### ISSUE THREAD

**Issue by ghale5011** [SabinAdhikari-Groot/collab-sprint1-final#2]
When getting gorm data from POST request, you should also include the phone number.
Code:
// Get form data from POST request
$firstName = $_POST['firstName'];
$lastName = $_POST['lastName'];
$email = $_POST['email'];
$password = $_POST['password'];

// Check if the email is already taken
$sql_check_email = "SELECT * FROM users WHERE email='$email'";
$result_check_email = $conn->query($sql_check_email);

**Comment by SabinAdhikari-Groot** [comment]
Thank you for the timely info. I have solved the issues that you highlighted previously.
