### ISSUE TITLE
Improper naming of database

### ISSUE THREAD

**Issue by psychpraphool** [SabinAdhikari-Groot/collab-sprint1-final#4]
Write the name of database and tables meaningful so it is understandable by all.
$host = "localhost";
$username = "root";
$password = "";
$database = "main_database";

$conn = new mysqli($host, $username, $password, $database);

if ($conn->connect_error) {
die("Connection failed: " . $conn->connect_error);
}

**Comment by SabinAdhikari-Groot** [comment]
I have noted the issue and changed the name of database to "hostel_management" successfully. If you have any other issues, please inform me.
